version: '3.7'

services:

  web:
    container_name: web
    build: .
    command: ["python3", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - .:/calistopia
    ports:
      - "8000:8000"

